### ISSUE TITLE
Не работает пример rest.py с токеном песочницы

### ISSUE THREAD

**Issue by YakovFat** [Awethon/open-api-python-client#6]
Здравствуйте, подскажите, почему может не работать пример rest.py с моим токеном песочницы, вот traceback:
Traceback (most recent call last):

  File "c:/Users/yakov/Desktop/open-api-python-client-master/examples/rest.py", line 7, in <module>
    client.sandbox.sandbox_clear_post()
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\api\sandbox_api.py", line 63, in sandbox_clear_post
    return self.sandbox_clear_post_with_http_info(**kwargs)  # noqa: E501
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\api\sandbox_api.py", line 142, in sandbox_clear_post_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\api_client.py", line 344, in call_api
    _preload_content, _request_timeout, _host)
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\api_client.py", line 175, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\api_client.py", line 388, in request
    body=body)
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\rest.py", line 277, in POST
    body=body)
  File "C:\Users\yakov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openapi_genclient\rest.py", line 230, in request
    raise ApiException(http_resp=r)
openapi_genclient.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Thu, 20 Feb 2020 18:19:57 GMT', 'Content-Type': 'application/json', 'Content-Length': '136', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'access-control-allow-methods': 'GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH', 'access-control-allow-headers': 'accept, content-type, authorization, access-control-allow-headers, x-requested-with', 'access-control-allow-origin': '*'})
HTTP response body: {"trackingId":"e69c5a55eeb5d817","payload":{"message":"Broker account not found for type=Tinkoff","code":"USER_ERROR"},"status":"Error"}

**Comment by kolfild26** [comment]
у меня такая же ошибка

> _Broker account not found for type=Tinkoff_

на строчке:
`client.sandbox.sandbox_clear_post()`

**Comment by Awethon** [comment]
@kolfild26 а брокерский счет Тинькофф (не ИИС) есть?

**Comment by kolfild26** [comment]
@Awethon 
конечно. обычный, не ИИС.

p.s. пример со streaming работает

**Comment by Awethon** [comment]
@kolfild26 кажется понял в чем ошибка, register надо вызвать до clear, спасибо, поправлю

**Comment by kolfild26** [comment]
@Awethon @YakovFat 
да, верно, так работает:

```
client = openapi.sandbox_api_client(token)
client.sandbox.sandbox_register_post()
client.sandbox.sandbox_clear_post()
client.sandbox.sandbox_currencies_balance_post(sandbox_set_currency_balance_request={"currency": "USD", "balance": 1000})

```
