### ISSUE TITLE
problem with client.sandbox.sandbox_clear_post() in rest.py

### ISSUE THREAD

**Issue by petrozzz** [Awethon/open-api-python-client#9]
Hi, I have problem with example rest.py: How can I fix it?

RESTART: D:\petro\invest_api\open-api-python-client-master\examples\rest.py 
Traceback (most recent call last):
  File "D:\petro\invest_api\open-api-python-client-master\examples\rest.py", line 7, in <module>
    client.sandbox.sandbox_clear_post()
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\api\sandbox_api.py", line 63, in sandbox_clear_post
    return self.sandbox_clear_post_with_http_info(**kwargs)  # noqa: E501
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\api\sandbox_api.py", line 142, in sandbox_clear_post_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\api_client.py", line 344, in call_api
    _preload_content, _request_timeout, _host)
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\api_client.py", line 175, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\api_client.py", line 388, in request
    body=body)
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\rest.py", line 277, in POST
    body=body)
  File "C:\Users\PS\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tinkoff_invest_openapi_client-0.0.7-py3.7.egg\openapi_genclient\rest.py", line 230, in request
    raise ApiException(http_resp=r)
openapi_genclient.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Thu, 12 Mar 2020 18:51:17 GMT', 'Content-Length': '0'})

**Comment by Awethon** [comment]
> File "D:\petro\invest_api\open-api-python-client-master\examples\rest.py", line 7, in 
> client.sandbox.sandbox_clear_post()

As you can see line 7 contains call of method `client.sandbox.sandbox_register_post()`
https://github.com/Awethon/open-api-python-client/blob/master/examples/rest.py#L7

Seems like an old master. Try to pull changes. 
If it doesn't help then try to reproduce your problem by calling the same methods here: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/
